export default {
  id: "cn",
  gitalkLangId: "zh-CN",
  langStrings: ["cn", "zh-CN", "zh"],
  detailedId: "zh-CN",
  name: "简体中文",
  definitions: {
    pageMedatadata: {
      homepage: "主页",
      articleList: "文章",
      description: "一个个人网站",
    },
    newContentPop: {
      refresh: "刷新",
      other: "以查看最新内容 :D",
    },
    headers: {
      home: "主页",
      articles: "文章",
      resume: "简历",
      slides: "幻灯片",
      articlePlans: "文章计划",
      about: {
        title: "关于",
        odyssey: "一个个人博客的史诗",
        project: "关于网站",
        me: "关于我",
      },
    },

    feedback: {
      title: "给我反馈！",
      paragraph1: "我很想听到大家对我网站的看法！",
      paragraph2: "如果你有什么想说的，请在下面的评论框留言！我将非常感谢！",
      paragraph3: "或者通过以下方式联系我！",
    },
    resources: {
      title: "资源",
      index: {
        documentTitle: "资源",
        title: "资源",
      },
      slides: {
        title: "幻灯片",
        description: "我做的演讲的幻灯片",
        autoGenerated: "以下内容根据 {} 中的内容自动生成。点击一项以进入对应GitHub目录。",
      },
      resume: {
        documentTitle: "简历",
        title: "简历",
      },
    },
    articlePlans: {
      title: "文章计划",
      description: "以下为目前计划编写和发布的文章。",
      articleTitle: "标题",
      tags: "标签",
      startTime: "列入计划时间",
      deadline: "预期发布时间",

    },
    search: {
      cardTitle: "搜索文章",
      inputPlaceholder: "在{}文章中搜索",
      notFound: "未找到",
      title: "{} 搜索结果",
      info: "结果数：{}",
    },
    footer: {
      codeBy: "本网站由{}自豪地编写",
      themedWith: "描绘主题",
      poweredBy: "强力驱动",
      license: "本站文章在{}协议下授权",
      contacts: "联系我",
      madeWithLove: "用 ❤ 制作",
      friendLinkhire: "如果您希望您的链接加入本站友情链接，请联系我！",
      runningTime: "博客已经运行 {} 天 {} 时 {} 分 {} 秒",
    },
    languageSelector: {
      select: "选择语言",
      switchingTo: "正在切换至: {}",
    },
    articleFrontmatter: {
      wordCount: "{} 字",
      timeToRead: "{} 分钟阅读",
      tagLinkTitle: "搜索带有{}标签的文章",
    },
    comments: {
      title: " 评论",
    },
    articlePage: {
      title: "文章",
      backToHome: "回到主页",
      selectLang: "选择一个文章语言",
      toc: "目录",
      share: {
        title: "分享",
      },
      relatedArticles: {
        text: "相关文章",
      },
      actions: {
        like: {
          like: "赞！",
          clicked: "谢谢！",
          liked: "已赞",
        },
        copyLink: {
          copyLink: "复制链接",
          copied: "已复制链接！",
        },
      },
    },
    articleItem: {
      availableLanguages: "可用语言：",
    },
    selfIntro: {
      author: "作者",
      university: "南京大学软件工程2016级本科生",
      resume: "简历",
      mailToMe: "ddadaal@outlook.com",
      more: "更多我的信息",
      moreLink: "更多",
    },
    blogIntro: {
      subtitle: "一个个人网站",
      description1: "基于Gatsby开发的静态网站",
      description2: "技术，代码，感悟和日常生活",
      sourceCode: "在GitHub上的博客源码",
      feedback: "反馈",
      lastUpdated: "上次更新于{}",
      more: "更多博客信息",
      moreLink: "更多",
    },
    statistics: {
      title: "统计信息",
      key: "统计项",
      value: "统计值",
      articleCount: "文章数：{}，总字数：{}",
      lastUpdated: "最后更新",

    },
    tagsCard: {
      title: "标签",
    },
    friends: {
      title: "朋友们",
    },

    homepage: {
      hello: "你好",
      from: "来自一个学生 | 程序员 | 有梦想的咸鱼",
      links: {
        articles: "文章 ({})",
        rss: "RSS",
        resume: "简历",
        slides: "幻灯片",
        aboutMe: "关于我",
        aboutProject: "关于网站",
        feedback: "反馈",
      },
    },
  },
};
