export default {
  id: "en",
  gitalkLangId: "en",
  langStrings: ["en", "en-US"],
  detailedId: "en-US",
  name: "English",
  definitions: {
    pageMedatadata: {
      homepage: "Home",
      articleList: "Articles",
      description: "a Personal Website",
    },
    newContentPop: {
      refresh: "Refresh",
      other: " to see new contents :D",
    },
    headers: {
      home: "Home",
      articles: "Articles",
      resume: "Resume",
      slides: "Slides",
      articlePlans: "Article Plans",
      about: {
        title: "About",
        odyssey: "The Odyssey",
        project: "About Website",
        me: "About Me",
      },
    },

    feedback: {
      title: "Feedback",
      paragraph1: "I am excited to hear from you guys!",
      paragraph2: "If you would like to say something, please don't hesitate to leave it down in the comment below! I would be greatly appreciated it if you did it!",
      paragraph3: "Or contact me through the following channels!",
    },
    resources: {
      title: "Resources",
      index: {
        documentTitle: "Resources",
        title: "Resources",
      },
      slides: {
        description: "The slides used in my presentations",
        title: "Slides",
        autoGenerated: "Contents are auto generated according to {}. Click to GitHub directory.",
      },
      resume: {
        documentTitle: "Resume",
        title: "Resume",
      },
    },
    articlePlans: {
      title: "Article Plans",
      description: "These are articles planned to be written and published.",
      articleTitle: "Title",
      tags: "Tags",
      startTime: "Plan Time",
      deadline: "Estimated Publish Time",

    },
    search: {
      cardTitle: "Search",
      inputPlaceholder: "Search in {} articles",
      notFound: "Not found.",
      title: "Search result for {}",
      info: "Number of results: {}",
    },
    footer: {
      codeBy: "Website coded proudly by {}",
      themedWith: "Themed with",
      poweredBy: "Powered by",
      license: "Articles are licensed under {}",
      contacts: "Contact me",
      madeWithLove: "Made with ❤",
      friends: "Friends",
      friendLinkhire: "Contact me if you'd like your website added to this list :D",
      runningTime: "Blog's been running for {} d {} h {} m {} s",
    },
    languageSelector: {
      select: "Select a language",
      switchingTo: "Switching to {}",
    },
    articlePage: {
      title: "Articles",
      backToHome: "Back to home",
      selectLang: "Select a language",
      toc: "Table of Contents",
      share: {
        title: "Share",
      },
      relatedArticles: {
        text: "Related Articles",
      },
      actions: {
        like: {
          like: "Like",
          clicked: "Thank you!",
          liked: "Liked!",
        },
        copyLink: {
          copyLink: "Copy Link",
          copied: "Link copied!",
        },
      },
    },
    articleFrontmatter: {
      wordCount: "{} words",
      timeToRead: "{} mins read",
      tagLinkTitle: "Search articles tagged with {}",
    },
    articleItem: {
      availableLanguages: "Available in ",
    },
    comments: {
      title: " Comments",
    },
    selfIntro: {
      author: "Author",
      university: "Undergraduate in Nanjing University Software Engineering since 2016",
      resume: "Resume",
      mailToMe: "ddadaal@outlook.com",
      more: "More about me",
      moreLink: "More",
    },
    blogIntro: {
      subtitle: "A Personal Website",
      description1: "A static website built with Gatsby",
      description2: "Technologies, experiences and daily life",
      sourceCode: "Blog Source Code on GitHub",
      feedback: "Feedback",
      lastUpdated: "Last updated in {}",
      more: "More about this website",
      moreLink: "More",
    },
    statistics: {
      title: "Statistics",
      key: "Key",
      value: "Value",
      articleCount: "Number of articles",
      lastUpdated: "Last updated",
    },
    tagsCard: {
      title: "Tags",

    },
    friends: {
      title: "Friends",
    },
    homepage: {
      hello: "Hello",
      from: "From a Student | Programmer | Dreamer",
      links: {
        articles: "Articles ({})",
        rss: "RSS",
        resume: "Resume",
        slides: "Slides",
        aboutMe: "About Me",
        aboutProject: "About Website",
        feedback: "Feedback",
      },
    },
  },
};
